import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';
import {SMAAPass} from 'three/addons/postprocessing/SMAAPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
const $=id=>document.getElementById(id), stage=$('stage'),plate=$('plate'),status=$('status');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;stage.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#d9d7cf');
const camera=new THREE.OrthographicCamera(-8,8,6, -6,.1,100);camera.position.set(-13.8,12.4,15);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.95,0);controls.enableDamping=true;controls.dampingFactor=.10;controls.minZoom=.65;controls.maxZoom=3.2;controls.minPolarAngle=.12;controls.maxPolarAngle=Math.PI*.485;controls.autoRotateSpeed=.42;controls.update();
scene.add(new THREE.HemisphereLight(0xe8edff,0x8a795a,1.7));
const sun=new THREE.DirectionalLight(0xffe3b0,3.1);sun.position.set(-5,10,4);sun.target.position.set(0,1,0);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);Object.assign(sun.shadow.camera,{left:-9,right:9,top:9,bottom:-9,near:.5,far:35});sun.shadow.normalBias=.018;sun.shadow.bias=-.00008;sun.shadow.radius=3;scene.add(sun,sun.target);
const fill=new THREE.DirectionalLight(0xd3e1ff,1.0);fill.position.set(4,7,-5);scene.add(fill);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:'#d9d7cf',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.418;ground.receiveShadow=true;scene.add(ground);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const ao=new SSAOPass(scene,camera,innerWidth,innerHeight);ao.ssaoMaterial.defines.PERSPECTIVE_CAMERA=0;ao.depthRenderMaterial.defines.PERSPECTIVE_CAMERA=0;ao.ssaoMaterial.needsUpdate=true;ao.depthRenderMaterial.needsUpdate=true;ao.kernelRadius=.26;ao.minDistance=.001;ao.maxDistance=.10;composer.addPass(ao);composer.addPass(new OutputPass());composer.addPass(new SMAAPass());
const views={hero:{p:[-13.8,12.4,15],t:[0,1.95,0],zoom:1,img:'竹溪小院_主视角.png'},garden:{p:[-10,7,10],t:[-2.7,1.8,.6],zoom:1.85,img:'竹溪小院_瓜架近景.png'},bridge:{p:[-.5,6,10.5],t:[3.1,1.6,1.4],zoom:2.00,img:'竹溪小院_溪桥近景.png'}};
let view='hero',mode='still',loaded=false,loading=false,transition=null,raf=0,disposed=false,dirty=true;
function render(){if(disposed)return;const u=ao.ssaoMaterial.uniforms;u.cameraProjectionMatrix.value.copy(camera.projectionMatrix);u.cameraInverseProjectionMatrix.value.copy(camera.projectionMatrixInverse);u.cameraNear.value=camera.near;u.cameraFar.value=camera.far;composer.render();}
function frame(now){raf=0;if(document.hidden)return;if(transition){const t=Math.min(1,(now-transition.start)/650),e=t*t*(3-2*t);camera.position.lerpVectors(transition.from,transition.to,e);controls.target.lerpVectors(transition.a,transition.b,e);camera.zoom=THREE.MathUtils.lerp(transition.z0,transition.z1,e);camera.updateProjectionMatrix();if(t===1)transition=null;}const changed=controls.update();if(mode==='explore'&&(dirty||changed||transition||controls.autoRotate)){render();dirty=false;}if(mode==='explore'&&(changed||transition||controls.autoRotate)&&!raf)raf=requestAnimationFrame(frame);}
function request(){if(!raf)raf=requestAnimationFrame(frame);}
controls.addEventListener('change',()=>{dirty=true;if(mode==='explore')request();});controls.addEventListener('start',()=>{transition=null;});
function load(){if(loading||loaded)return;loading=true;status.textContent='正在展开这座小院…';new GLTFLoader().setDRACOLoader(new DRACOLoader().setDecoderPath('./node_modules/three/examples/jsm/libs/draco/gltf/')).load('./竹溪小院.glb',g=>{g.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){m.side=THREE.DoubleSide;}}}});scene.add(g.scene);loaded=true;loading=false;status.textContent='';window.sceneReady=true;renderer.compile(scene,camera);render();request();},p=>{if(p.total)status.textContent=`正在展开这座小院… ${Math.round(p.loaded/p.total*100)}%`;},e=>{console.error(e);loading=false;status.textContent='模型未能载入，请检查本地服务后刷新。';});}
function setMode(next){mode=next;plate.classList.toggle('hidden',next==='explore');$('still').classList.toggle('active',next==='still');$('explore').classList.toggle('active',next==='explore');$('hint').textContent=next==='still'?'光线追踪 · 午后暖阳':'拖动旋转 · 滚轮缩放 · 右键平移';if(next==='explore'){load();render();request();}else{controls.autoRotate=false;$('spin').classList.remove('active');}}
function go(key){view=key;const v=views[key];plate.src='../renders/'+v.img;document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===key));transition={start:performance.now(),from:camera.position.clone(),to:new THREE.Vector3(...v.p),a:controls.target.clone(),b:new THREE.Vector3(...v.t),z0:camera.zoom,z1:v.zoom};if(matchMedia('(prefers-reduced-motion: reduce)').matches){transition.start-=700;}request();}
$('still').onclick=()=>setMode('still');$('explore').onclick=()=>setMode('explore');document.querySelectorAll('[data-view]').forEach(el=>el.onclick=()=>go(el.dataset.view));$('spin').onclick=()=>{setMode('explore');controls.autoRotate=!controls.autoRotate;$('spin').classList.toggle('active',controls.autoRotate);request();};$('save').onclick=()=>{const a=document.createElement('a');a.download='竹溪小院.png';if(mode==='still'){a.href=plate.src;}else{render();a.href=renderer.domElement.toDataURL('image/png');}a.click();};
function resize(){const aspect=innerWidth/innerHeight,h=Math.max(13.7,16.8/aspect);camera.left=-h*aspect/2;camera.right=h*aspect/2;camera.top=h/2;camera.bottom=-h/2;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);render();}
window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden){if(raf)cancelAnimationFrame(raf);raf=0;}else{render();request();}});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();status.textContent='图形上下文暂时中断，请刷新恢复。';});window.addEventListener('pagehide',()=>{disposed=true;cancelAnimationFrame(raf);controls.dispose();composer.dispose();renderer.dispose();});
window.viewer={setMode,go,get state(){return {mode,view,loaded,meshes:renderer.info.memory.geometries,zoom:camera.zoom};}};resize();
