import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';
import {SMAAPass} from 'three/addons/postprocessing/SMAAPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {installSoftSunShadows,createSkyEnvironment,patchMotionMaterial,tuneMaterial} from './surface-v2.js';
import {createStream,createWakes} from './water-v2.js';
import {duckPose,peckAngle,windOffset,riverCenter,riverHalfWidth} from './motion.js';
installSoftSunShadows();
const $=id=>document.getElementById(id),stage=$('stage'),plate=$('plate'),status=$('status');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.shadowMap.autoUpdate=false;renderer.localClippingEnabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.00;stage.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#dedbd2');const env=createSkyEnvironment(renderer);scene.environment=env.texture;
const camera=new THREE.OrthographicCamera(-8,8,6,-6,.1,100);camera.position.set(-13.8,12.4,15);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.95,0);controls.enableDamping=true;controls.dampingFactor=.12;controls.minZoom=.65;controls.maxZoom=3.2;controls.minPolarAngle=.12;controls.maxPolarAngle=Math.PI*.485;controls.autoRotateSpeed=.42;controls.update();
scene.add(new THREE.HemisphereLight(0xcadfff,0x8a724c,.24));
const sun=new THREE.DirectionalLight(0xffe2b3,4.15);sun.position.set(-5,8,4);sun.target.position.set(0,0,0);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);Object.assign(sun.shadow.camera,{left:-9,right:9,top:9,bottom:-9,near:.5,far:35});sun.shadow.normalBias=.010;sun.shadow.bias=-.000045;scene.add(sun,sun.target);
const fill=new THREE.DirectionalLight(0xc6dcff,.14);fill.position.set(4,7,-5);scene.add(fill);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:'#bdb7a8',roughness:1,envMapIntensity:.18}));ground.rotation.x=-Math.PI/2;ground.position.y=-.418;ground.receiveShadow=true;scene.add(ground);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const ao=new SSAOPass(scene,camera,innerWidth,innerHeight);ao.ssaoMaterial.defines.PERSPECTIVE_CAMERA=0;ao.depthRenderMaterial.defines.PERSPECTIVE_CAMERA=0;ao.ssaoMaterial.needsUpdate=true;ao.depthRenderMaterial.needsUpdate=true;ao.kernelRadius=.34;ao.minDistance=.001;ao.maxDistance=.075;composer.addPass(ao);composer.addPass(new OutputPass());composer.addPass(new SMAAPass());
// Match normal/depth passes to each moving surface so contact occlusion follows the current pose.
const noAO=[];const oldOverride=ao._overrideVisibility.bind(ao);ao._overrideVisibility=()=>{oldOverride();for(const o of noAO){if(o.visible){o.visible=false;ao._visibilityCache.push(o);}}};
ao._renderOverride=function(renderer,overrideMaterial,renderTarget,clearColor,clearAlpha){
 const previousColor=renderer.getClearColor(new THREE.Color()),previousAlpha=renderer.getClearAlpha(),auto=renderer.autoClear;
 renderer.setRenderTarget(renderTarget);renderer.autoClear=false;renderer.setClearColor(clearColor??0,clearAlpha??0);renderer.clear();const saved=[];
 scene.traverse(o=>{if(o.isMesh&&o.visible){saved.push([o,o.material]);o.material=o.userData.aoNormal||overrideMaterial;}});
 renderer.render(scene,camera);for(const [o,m] of saved)o.material=m;renderer.autoClear=auto;renderer.setClearColor(previousColor,previousAlpha);
};
const views={hero:{p:[-13.8,12.4,15],t:[0,1.95,0],zoom:1,img:'竹溪小院_主视角.png'},garden:{p:[-10,7,10],t:[-2.7,1.8,.6],zoom:1.85,img:'竹溪小院_瓜架近景.png'},bridge:{p:[-.5,6,10.5],t:[3.1,1.6,1.4],zoom:2,img:'竹溪小院_溪桥近景.png'}};
let view='hero',mode='explore',loaded=false,loading=false,transition=null,raf=0,disposed=false,dirty=true,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,time=0,lastNow=0,lastRender=0,lastShadow=-100,stream=null,wakes=null,model=null;
const actors=[],ducks=[],motionUniforms=[];
function applyMotion(){for(const a of actors){if(a.type==='duck'){const p=duckPose(time,a.index);a.object.position.set(p.x,p.y,p.z);a.object.rotation.set(0,p.heading,p.roll);}else a.uniforms.uPeck.value=peckAngle(time,a.index,a.type==='hen');}for(const u of motionUniforms)u.uSceneTime.value=time;if(wakes)wakes.update(time);scene.updateMatrixWorld(true);}
function render(force=false){if(disposed)return;applyMotion();if(force||time-lastShadow>.10||lastShadow<0){renderer.shadowMap.needsUpdate=true;lastShadow=time;}const u=ao.ssaoMaterial.uniforms;u.cameraProjectionMatrix.value.copy(camera.projectionMatrix);u.cameraInverseProjectionMatrix.value.copy(camera.projectionMatrixInverse);u.cameraNear.value=camera.near;u.cameraFar.value=camera.far;
 // First render builds the shadow map, then the reflection can sample it.
 if(stream&&sun.shadow.map)stream.update(time,force);composer.render();}
function frame(now){raf=0;if(disposed||document.hidden)return;const dt=lastNow?Math.min((now-lastNow)/1000,.10):0;lastNow=now;if(mode==='explore'&&playing&&loaded)time+=dt;if(transition){const t=Math.min(1,(now-transition.start)/650),e=t*t*(3-2*t);camera.position.lerpVectors(transition.from,transition.to,e);controls.target.lerpVectors(transition.a,transition.b,e);camera.zoom=THREE.MathUtils.lerp(transition.z0,transition.z1,e);camera.updateProjectionMatrix();if(t===1)transition=null;}
 const changed=controls.update();if(mode==='explore'&&loaded&&(dirty||changed||transition||controls.autoRotate||playing)&&now-lastRender>30){render();dirty=false;lastRender=now;}
 if(mode==='explore'&&(playing||changed||transition||controls.autoRotate||dirty))request();}
function request(){if(!raf&&!disposed)raf=requestAnimationFrame(frame);}
controls.addEventListener('change',()=>{dirty=true;stream?.dirty();if(mode==='explore')request();});controls.addEventListener('start',()=>{transition=null;});
function windKind(name){return /wind_bamboo|竹叶飞簇|竹节环|竹秆_|竹枝/.test(name)?2:/wind_vine|掌叶攀覆|攀缘藤|棚上纵横/.test(name)?3:/wind_flower|wind_grass|五瓣花簇|花境叶片|凤仙花茎|花心|溪岸花|溪岸黄|草丛高低层|树根莎草/.test(name)?4:/wind_tree|榆树分层叶冠|一级分枝|二级细枝/.test(name)?1:0;}
function load(){if(loading||loaded)return;loading=true;status.textContent='正在展开这座小院…';new GLTFLoader().setDRACOLoader(new DRACOLoader().setDecoderPath('./node_modules/three/examples/jsm/libs/draco/gltf/')).load('./竹溪小院_动态.glb',g=>{model=g.scene;
 model.traverse(o=>{if(o.name.startsWith('actor_')){const type=o.name.includes('duck')?'duck':o.name.includes('chick')?'chick':'hen',index=type==='hen'?0:Number(o.name.split('_').at(-1))-1;const uniforms={uSceneTime:{value:0},uWindKind:{value:0},uPeck:{value:0},uBirdKind:{value:type==='hen'?1:type==='chick'?2:0}};o.userData.actor={object:o,type,index,uniforms};actors.push(o.userData.actor);motionUniforms.push(uniforms);if(type==='duck')ducks[index]=o;}});
 model.traverse(o=>{if(!o.isMesh)return;if(/water_replace|wake_replace|蜿蜒溪水|鸭后涟漪/.test(o.name)){o.visible=false;return;}o.castShadow=true;o.receiveShadow=true;let ancestor=o.parent,actor=null;while(ancestor){if(ancestor.userData.actor){actor=ancestor.userData.actor;break;}ancestor=ancestor.parent;}
 const wk=windKind(o.name),uniforms=actor?.uniforms||{uSceneTime:{value:0},uWindKind:{value:wk},uPeck:{value:0},uBirdKind:{value:0}};const moving=!!actor||wk>0;if(moving){if(!actor)motionUniforms.push(uniforms);o.frustumCulled=false;}
 const convert=mat=>{const m=tuneMaterial(mat.clone(),mat.name);m.side=THREE.DoubleSide;if(moving)patchMotionMaterial(m,uniforms);return m;};o.material=Array.isArray(o.material)?o.material.map(convert):convert(o.material);
 if(moving)o.userData.aoNormal=patchMotionMaterial(new THREE.MeshNormalMaterial({side:THREE.DoubleSide}),uniforms);
 if(moving)o.customDepthMaterial=patchMotionMaterial(new THREE.MeshDepthMaterial({depthPacking:THREE.RGBADepthPacking,side:THREE.DoubleSide}),uniforms);
 });scene.add(model);stream=createStream(renderer,scene,camera,sun);wakes=createWakes(scene,ducks);stream.excluded.push(...wakes.objects);noAO.push(stream.water,...wakes.objects);loaded=true;loading=false;status.textContent='';window.sceneReady=true;render(true);stream.dirty();render(true);plate.classList.toggle('hidden',mode==='explore');lastNow=0;request();},p=>{if(p.total)status.textContent=`正在展开这座小院… ${Math.round(p.loaded/p.total*100)}%`;},e=>{console.error(e);loading=false;status.textContent='模型未能载入，请检查本地服务后刷新。';});}
function setMode(next){mode=next;plate.classList.toggle('hidden',next==='explore'&&loaded);$('still').classList.toggle('active',next==='still');$('explore').classList.toggle('active',next==='explore');$('hint').textContent=next==='still'?'光线追踪 · 午后暖阳':'拖动旋转 · 滚轮缩放 · 右键平移';$('motion').disabled=next==='still';lastNow=0;if(next==='explore'){load();dirty=true;request();}else{controls.autoRotate=false;$('spin').classList.remove('active');}}
function go(key){view=key;const v=views[key];plate.src='../renders/'+v.img;document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===key));transition={start:performance.now(),from:camera.position.clone(),to:new THREE.Vector3(...v.p),a:controls.target.clone(),b:new THREE.Vector3(...v.t),z0:camera.zoom,z1:v.zoom};if(matchMedia('(prefers-reduced-motion: reduce)').matches)transition.start-=700;dirty=true;request();}
function setPlaying(value){playing=value;$('motion').textContent=value?'暂停动态':'继续动态';$('motion').setAttribute('aria-pressed',String(!value));lastNow=0;dirty=true;request();}
$('still').onclick=()=>setMode('still');$('explore').onclick=()=>setMode('explore');$('motion').onclick=()=>setPlaying(!playing);document.querySelectorAll('[data-view]').forEach(el=>el.onclick=()=>go(el.dataset.view));$('spin').onclick=()=>{setMode('explore');controls.autoRotate=!controls.autoRotate;$('spin').classList.toggle('active',controls.autoRotate);request();};$('save').onclick=()=>{const a=document.createElement('a');a.download='竹溪小院.png';if(mode==='still')a.href=plate.src;else{render(true);a.href=renderer.domElement.toDataURL('image/png');}a.click();};
function resize(){const aspect=innerWidth/innerHeight,h=Math.max(13.7,16.8/aspect);camera.left=-h*aspect/2;camera.right=h*aspect/2;camera.top=h/2;camera.bottom=-h/2;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);stream?.dirty();dirty=true;if(loaded)render(true);request();}
window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{lastNow=0;if(document.hidden){if(raf)cancelAnimationFrame(raf);raf=0;}else{dirty=true;request();}});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();status.textContent='图形上下文暂时中断，请刷新恢复。';});window.addEventListener('pagehide',()=>{disposed=true;cancelAnimationFrame(raf);controls.dispose();composer.dispose();stream?.dispose();env.dispose();renderer.dispose();});
window.viewer={setMode,go,setPlaying,setTime(t){setPlaying(false);time=t;render(true);},duckPose,peckAngle,windOffset,riverCenter,riverHalfWidth,get state(){return {mode,view,loaded,playing,time,meshes:renderer.info.memory.geometries,zoom:camera.zoom,actors:actors.map(a=>({name:a.object.name,type:a.type,index:a.index,position:a.object.position.toArray(),rotation:a.object.rotation.toArray(),peck:a.uniforms.uPeck.value})),movingGroups:motionUniforms.length};},scene,camera,renderer,stream:()=>stream};resize();setPlaying(playing);setMode('explore');
