const {chromium}=require('playwright');
const path=require('path'),fs=require('fs');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});const errors=[],requests=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});page.on('request',r=>requests.push(r.url()));
await page.goto('http://127.0.0.1:8770/preview/',{waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelector('#plate').naturalWidth>0);await page.screenshot({path:path.join(__dirname,'../verification/browser_still.png')});
await page.locator('#explore').click();await page.waitForFunction(()=>window.sceneReady===true,null,{timeout:120000});await page.waitForTimeout(900);await page.screenshot({path:path.join(__dirname,'../verification/browser_final_hero.png')});
const loaded=await page.evaluate(()=>window.viewer.state);await page.mouse.move(770,450);await page.mouse.down();await page.mouse.move(970,540,{steps:15});await page.mouse.up();await page.waitForTimeout(600);await page.mouse.wheel(0,-400);await page.waitForTimeout(600);const zoomed=await page.evaluate(()=>window.viewer.state);
await page.locator('[data-view="garden"]').click();await page.waitForTimeout(850);await page.screenshot({path:path.join(__dirname,'../verification/browser_garden.png')});const garden=await page.evaluate(()=>window.viewer.state);
await page.locator('[data-view="bridge"]').click();await page.waitForTimeout(850);const bridge=await page.evaluate(()=>window.viewer.state);
await page.locator('#spin').click();await page.waitForTimeout(500);await page.locator('#spin').click();
const dl=page.waitForEvent('download');await page.locator('#save').click();const download=await dl;await download.saveAs(path.join(__dirname,'../verification/browser_saved.png'));
await page.setViewportSize({width:900,height:1200});await page.locator('[data-view="hero"]').click();await page.waitForTimeout(850);await page.screenshot({path:path.join(__dirname,'../verification/browser_portrait.png')});
await page.locator('#still').click();for(const v of ['garden','bridge','hero']){await page.locator(`[data-view="${v}"]`).click();await page.waitForFunction(()=>document.querySelector('#plate').complete&&document.querySelector('#plate').naturalWidth>0);}
await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelector('#plate').naturalWidth>0);
const report={loaded,zoomed,garden,bridge,download:download.suggestedFilename(),errors,localOnly:requests.every(u=>u.startsWith('http://127.0.0.1:8770/')||u.startsWith('data:')||u.startsWith('blob:http://127.0.0.1:8770/')),tested:['still images','load GLB','orbit drag','continuous zoom','garden preset','bridge preset','automatic orbit toggle','PNG save','portrait resize','still-mode switches','reload']};fs.writeFileSync(path.join(__dirname,'../verification/browser-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();})();
